### ISSUE TITLE
这个翻译是认真的吗

### ISSUE THREAD

**Issue by end-cycle** [vuejs-translations/docs-zh-cn#896]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

译法讨论

### 问题描述

src/index.md
![](https://github.com/vuejs-translations/docs-zh-cn/assets/62703840/110a6975-6060-4713-b808-946b82bb375e)

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/62703840/0fcc1851-facd-48a1-a8a5-e19690b07404)

威优易

朋友发给我的时候还以为是什么国产套壳框架，没想到还真是vue，我诚恳的想了解为什么要改成这样。
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/vuejs-translations/docs-zh-cn/issues/895
```
