### ISSUE TITLE
Update computed.md

### ISSUE THREAD

**Issue by 1109176988** [vuejs-translations/docs-zh-cn#952]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

I hope that in the Chinese document on this page of computed, the word computed-caching-vs-methods is changed to Computed-Caching-vs-function-Methods. The word "计算属性缓存 vs 方法" is changed to "计算属性缓存 vs function方法", and the word "方法" used in this document should be changed to the original word "function".

Why?
Because when I look at the document, I don't know what a "method" Chinese character suddenly appears, and I don't know what it is talking about or what it refers to. The problem here is that the noun machine in the code should not be translated into Chinese, which makes some Chinese readers feel that they don't understand the meaning of this word. I suggest that the code vocabulary, nouns or words of the document should be directly put into the document. When readers look at function or watch, they will immediately understand that it is a method or a monitoring event. If the word "method" is mechanically translated, readers will not understand what it means for a while.
```[tasklist]
### Tasks
```

**Comment by Justineo** [comment]
See https://github.com/vuejs-translations/docs-zh-cn/pull/950#issuecomment-2130972419.
